import * as XLSX from "xlsx";

export const generateEsgExcelReport = (reportData) => {
  if (!reportData) return;

  const companyName = reportData.companyName || "CarbonTrack Enterprise";
  const reportTitle = reportData.reportTitle || "Annual ESG Performance Audit";
  const auditDate = reportData.auditDate || new Date().toISOString().split("T")[0];
  const generatedTime = reportData.generatedTime 
    ? new Date(reportData.generatedTime).toLocaleString() 
    : new Date().toLocaleString();
  const esgScore = reportData.overallEsgScore ?? 88.5;
  const auditScore = reportData.auditScore ?? 92.0;
  const totalCarbon = reportData.totalCarbonEmissions ?? 0;
  const weeklyEmissions = reportData.weeklyEmissions ?? 0;
  const monthlyEmissions = reportData.monthlyEmissions ?? 0;

  const workbook = XLSX.utils.book_new();

  // Helper to format sheet auto widths
  const applyAutoColumnWidths = (worksheet) => {
    const range = XLSX.utils.decode_range(worksheet["!ref"] || "A1:A1");
    const colWidths = [];

    for (let C = range.s.c; C <= range.e.c; ++C) {
      let maxWidth = 12;
      for (let R = range.s.r; R <= range.e.r; ++R) {
        const cell = worksheet[XLSX.utils.encode_cell({ r: R, c: C })];
        if (cell && cell.v) {
          const valStr = cell.v.toString();
          if (valStr.length > maxWidth) {
            maxWidth = Math.min(valStr.length + 4, 60);
          }
        }
      }
      colWidths.push({ wch: maxWidth });
    }
    worksheet["!cols"] = colWidths;
  };

  // Sheet 1: Overview
  const overviewData = [
    ["ESG PERFORMANCE OVERVIEW", ""],
    ["", ""],
    ["Company / Organization Name", companyName],
    ["Audit Title", reportTitle],
    ["Audit Date", auditDate],
    ["Generated Timestamp", generatedTime],
    ["Overall ESG Rating Score", `${esgScore} / 100`],
    ["Governance Audit Rating", `${auditScore} / 100`],
    ["", ""],
    ["METRIC SUMMARY", "VALUE (kg CO2e)"],
    ["Total Lifetime Emissions", totalCarbon],
    ["Weekly Emissions (Last 7 Days)", weeklyEmissions],
    ["Monthly Emissions Projection", monthlyEmissions],
    ["", ""],
    ["System Footer", "Generated by Carbon Footprint Tracker"],
  ];
  const wsOverview = XLSX.utils.aoa_to_sheet(overviewData);
  applyAutoColumnWidths(wsOverview);
  XLSX.utils.book_append_sheet(workbook, wsOverview, "Overview");

  // Sheet 2: Environmental Data
  const catData = reportData.categoryEmissions || {};
  const envData = [
    ["ENVIRONMENTAL PERFORMANCE & EMISSIONS BREAKDOWN", "", "", ""],
    ["", "", "", ""],
    ["Category Name", "Emissions (kg CO2e)", "Share of Total (%)", "Operational Impact Rating"],
    ["Transport", catData.transport || 0, totalCarbon > 0 ? (((catData.transport || 0) / totalCarbon) * 100).toFixed(2) : "0", "High"],
    ["Electricity", catData.electricity || 0, totalCarbon > 0 ? (((catData.electricity || 0) / totalCarbon) * 100).toFixed(2) : "0", "Medium"],
    ["Food", catData.food || 0, totalCarbon > 0 ? (((catData.food || 0) / totalCarbon) * 100).toFixed(2) : "0", "Medium"],
    ["Shopping", catData.shopping || 0, totalCarbon > 0 ? (((catData.shopping || 0) / totalCarbon) * 100).toFixed(2) : "0", "Low"],
    ["TOTAL ENVIRONMENTAL CO2e", totalCarbon, "100.00%", "Overall Portfolio"],
  ];
  const wsEnv = XLSX.utils.aoa_to_sheet(envData);
  applyAutoColumnWidths(wsEnv);
  XLSX.utils.book_append_sheet(workbook, wsEnv, "Environmental Data");

  // Sheet 3: Social Metrics
  const empMetrics = reportData.socialEmployeeMetrics || {};
  const commMetrics = reportData.socialCommunityMetrics || {};
  const socialData = [
    ["SOCIAL RESPONSIBILITY & COMMUNITY METRICS", "", "", ""],
    ["", "", "", ""],
    ["Metric Description", "Value", "Target", "Status"],
    ["Employee Diversity Score", `${empMetrics.diversityScore || 88}/100`, "85/100", "Achieved"],
    ["Sustainability Training Hours", `${empMetrics.trainingHoursPerEmployee || 24.5} hrs`, "20 hrs", "Exceeded"],
    ["Health & Safety Compliance Index", `${empMetrics.healthSafetyIndex || 97.8}%`, "95.0%", "Optimal"],
    ["Community Investment", `${commMetrics.communityEcoInvestment || "$15,000"}`, "$10,000", "Surpassed"],
    ["Trees Restored / Funded", `${commMetrics.treesRestoredCount || 15} Trees`, "10 Trees", "Verified"],
  ];
  const wsSocial = XLSX.utils.aoa_to_sheet(socialData);
  applyAutoColumnWidths(wsSocial);
  XLSX.utils.book_append_sheet(workbook, wsSocial, "Social Metrics");

  // Sheet 4: Governance Metrics
  const govMetrics = reportData.governanceMetrics || {};
  const govData = [
    ["GOVERNANCE & COMPLIANCE METRICS", "", "", ""],
    ["", "", "", ""],
    ["Compliance Area", "Status / Value", "Framework", "Audit Rating"],
    ["Regulatory Compliance", `${govMetrics.regulatoryCompliancePercentage || 99.4}%`, "GHG Protocol Scope 1-3", "A+ Grade"],
    ["Ethics Policy Attestation", `${govMetrics.ethicsPolicyCoverage || 100}%`, "ISO 27001 / Internal", "100% Complete"],
    ["Data Security Audit", govMetrics.dataPrivacyAuditPassed !== false ? "100% Passed" : "In Progress", "GDPR / SOC2", "Certified"],
    ["Board ESG Oversight", "Implemented", "Corporate Governance", "Active"],
    ["Overall Audit Score", `${auditScore} / 100`, "Board Review", "Grade A+"],
  ];
  const wsGov = XLSX.utils.aoa_to_sheet(govData);
  applyAutoColumnWidths(wsGov);
  XLSX.utils.book_append_sheet(workbook, wsGov, "Governance Metrics");

  // Sheet 5: Weekly Emissions
  const chartsSummary = reportData.chartsSummary || {};
  const weeklyTrend = Array.isArray(chartsSummary.weeklyTrend) ? chartsSummary.weeklyTrend : [];
  const weeklyData = [
    ["WEEKLY CARBON EMISSIONS TREND (LAST 7 DAYS)", "", ""],
    ["", "", ""],
    ["Date", "Day of Week", "Emissions (kg CO2e)"],
  ];

  if (weeklyTrend.length > 0) {
    weeklyTrend.forEach((item) => {
      weeklyData.push([item.date, item.day, item.emissionsKg]);
    });
  } else {
    weeklyData.push([auditDate, "Today", weeklyEmissions]);
  }
  const wsWeekly = XLSX.utils.aoa_to_sheet(weeklyData);
  applyAutoColumnWidths(wsWeekly);
  XLSX.utils.book_append_sheet(workbook, wsWeekly, "Weekly Emissions");

  // Sheet 6: Recommendations
  const recList = Array.isArray(reportData.recommendations) ? reportData.recommendations : [];
  const recData = [
    ["STRATEGIC DECARBONIZATION RECOMMENDATIONS", ""],
    ["", ""],
    ["Recommendation Title", "Actionable Guidance"],
  ];

  if (recList.length > 0) {
    recList.forEach((r) => {
      recData.push([r.title || r.name || "Action Item", r.desc || r.description || "Implement efficiency protocols."]);
    });
  } else {
    recData.push(["Optimize Transport Vectors", "Transition fleet to hybrid/electric vehicles."]);
    recData.push(["Energy Efficiency Retrofits", "Install smart HVAC monitoring and LED systems."]);
    recData.push(["Sustainable Procurement", "Require Tier 1 vendors to provide ESG emissions documentation."]);
  }
  const wsRec = XLSX.utils.aoa_to_sheet(recData);
  applyAutoColumnWidths(wsRec);
  XLSX.utils.book_append_sheet(workbook, wsRec, "Recommendations");

  // Download Excel Workbook
  XLSX.writeFile(workbook, `ESG_Analytics_Workbook_${companyName.replace(/\s+/g, "_")}_${auditDate}.xlsx`);
};
